#! /bin/bash

set -eu

lapt_dir=$(dirname $(readlink -f $0))
ldpkg=$lapt_dir/ldpkg
log=$lapt_dir/lapt_log
pkg_util=$lapt_dir/pkg_util
LAPT_DOWNLOADS=$($ldpkg get_dir)/lapt_downloads
export LAPT_LOG_LEVEL=${LAPT_LOG_LEVEL-0}

declare -a public_commands private_commands
public_commands=(install)
private_commands=(list_commands) # available, but not shown in list_commands

source $lapt_dir/color_palette
source $lapt_dir/lapt_functions

function accept_command() {
    local command=$1
    local candidate
    for candidate in "${public_commands[@]}" "${private_commands[@]}"; do
        if [ "$candidate" == "$command" ]; then
            return 0
        fi
    done
    return 1
}

if [ $# = 0 ]; then
    $log "{RED}[Error]${ENDCOLOR} Input command" >&2
    exit 1
fi

command=$1
if ! accept_command "$command"; then
    echo "Invalid command" >&2
fi

shift

OPT_FORCE_INSTALL=false
OPT_INSTALL_FROM_DEB=false
OPTARG_DEB_FILENAME=
while getopts fd: OPT; do
    case $OPT in
        f) OPT_FORCE_INSTALL=true;;
        d) OPT_INSTALL_FROM_DEB=true
           OPTARG_DEB_FILENAME=$OPTARG;;
        \?) echo "Invalid option"
            exit 1;;
    esac
done

shift $((OPTIND - 1))

lapt_"$command" "$@"
