#! /bin/bash

set -eu

lapt_dir=$(dirname $(readlink -f $0))
ldpkg=$lapt_dir/ldpkg
log=$lapt_dir/lapt-log
LAPT_DOWNLOADS=$($ldpkg get_dir)/lapt_downloads
export LAPT_LOG_LEVEL=${LAPT_LOG_LEVEL-0}

declare -a public_commands private_commands
public_commands=(install finstall install_deb)
private_commands=(list_commands) # available, but not shown in list_commands

source $lapt_dir/color_palette
source $lapt_dir/lapt_functions

function accept_command() {
    local command=$1
    local candidate
    for candidate in "${public_commands[@]}" "${private_commands[@]}"; do
        if [ "$candidate" == "$command" ]; then
            return 0
        fi
    done
    return 1
}

if [ $# = 0 ]; then
    $log "{RED}[Error]${ENDCOLOR} Input command" >&2
    exit 1
fi

command=$1
shift

if ! accept_command "$command"; then
    echo "Invalid command" >&2
fi

command_install=install
if [ "$command" == finstall ]; then
    # 主にテスト用
    command=install
    command_install=finstall
    FORCE_INSTALL=true
fi

lapt_"$command" "$@"
